delimiter $$

CREATE TABLE `s_user` (
  `USERID` varchar(50) NOT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `DEPT` varchar(50) DEFAULT NULL,
  `SECTION` varchar(50) DEFAULT NULL,
  `ZW` varchar(100) DEFAULT NULL,
  `ROLE` varchar(20) DEFAULT '0',
  `SYS_RESERVER1` varchar(50) DEFAULT NULL,
  `SYS_RESERVER2` varchar(50) DEFAULT NULL,
  `SYS_RESERVER3` varchar(500) DEFAULT NULL,
  `SYS_RESERVER4` varchar(50) DEFAULT NULL,
  `SYS_RESERVER5` varchar(50) DEFAULT NULL,
  `SYS_RESERVER6` varchar(50) DEFAULT NULL,
  `SYS_RESERVER7` varchar(50) DEFAULT NULL,
  `SYS_RESERVER8` varchar(50) DEFAULT NULL,
  `SYS_RESERVER9` varchar(50) DEFAULT NULL,
  `SYS_RESERVER10` varchar(50) DEFAULT NULL,
  `SYS_RESERVER11` varchar(50) DEFAULT NULL,
  `SYS_RESERVER12` varchar(50) DEFAULT '0',
  `SYS_RESERVER13` varchar(50) DEFAULT NULL,
  `SYS_RESERVER14` varchar(50) DEFAULT NULL,
  `SYS_RESERVER15` varchar(50) DEFAULT NULL,
  `SYS_RESERVER16` varchar(50) DEFAULT NULL,
  `SYS_RESERVER17` varchar(50) DEFAULT NULL,
  `SYS_RESERVER18` date DEFAULT NULL,
  `SYS_RESERVER19` varchar(50) DEFAULT NULL,
  `SYS_RESERVER20` varchar(50) DEFAULT NULL,
  `SYS_RESERVER21` varchar(250) DEFAULT NULL,
  `SYS_RESERVER22` varchar(50) DEFAULT NULL,
  `SYS_RESERVER23` varchar(50) DEFAULT NULL,
  `SYS_RESERVER24` varchar(50) DEFAULT NULL,
  `SYS_RESERVER25` varchar(50) DEFAULT NULL,
  `CREATEDBYUSER` varchar(50) DEFAULT NULL,
  `CREATEDTIME` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `s_user_grantfunctions` (
  `S_USER_GRANTFUNCTIONSID` varchar(50) NOT NULL,
  `USERID` varchar(50) NOT NULL,
  `FUNCTIONID` varchar(20) NOT NULL,
  `CREATEDBYUSER` varchar(50) DEFAULT NULL,
  `CREATEDTIME` date DEFAULT NULL,
  `SYS_RESERVER1` varchar(100) DEFAULT NULL,
  `SYS_RESERVER2` varchar(100) DEFAULT NULL,
  `SYS_RESERVER3` varchar(100) DEFAULT NULL,
  `SYS_RESERVER4` varchar(50) DEFAULT NULL,
  `SYS_RESERVER5` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `s_user_role` (
  `GROUPID` varchar(50) NOT NULL,
  `GROUPNAME` varchar(100) DEFAULT NULL,
  `DEPT` varchar(50) DEFAULT NULL,
  `SYS_RESERVER1` varchar(50) DEFAULT NULL,
  `SYS_RESERVER2` varchar(50) DEFAULT NULL,
  `SYS_RESERVER3` varchar(50) DEFAULT NULL,
  `SYS_RESERVER4` varchar(50) DEFAULT NULL,
  `SYS_RESERVER5` varchar(50) DEFAULT NULL,
  `SYS_RESERVER6` varchar(50) DEFAULT NULL,
  `SYS_RESERVER7` varchar(50) DEFAULT NULL,
  `SYS_RESERVER8` varchar(50) DEFAULT NULL,
  `SYS_RESERVER9` varchar(50) DEFAULT NULL,
  `SYS_RESERVER10` varchar(50) DEFAULT NULL,
  `CREATEDBYUSER` varchar(50) DEFAULT NULL,
  `CREATEDTIME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


delimiter $$

CREATE TABLE `s_user_userroles` (
  `S_USER_USERROLESID` varchar(50) NOT NULL,
  `USERID` varchar(50) NOT NULL,
  `GROUPID` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$


